### ISSUE TITLE
error on clean install (java 1.8.0_20)

### ISSUE THREAD

**Issue by vitormmendes** [rodolfodpk/myeslib2#5]
When running clean install is :

myeslib2/myeslib2-core/src/main/java/org/myeslib/data/UnitOfWork.java:[47,45] no suitable method found for collect(java.util.stream.Collector<java.lang.Object,capture#1 of ?,java.util.LinkedList<java.lang.Object>>)
    method java.util.stream.Stream.<R>collect(java.util.function.Supplier<R>,java.util.function.BiConsumer<R,? super capture#2 of ? extends org.myeslib.core.Event>,java.util.function.BiConsumer<R,R>) is not applicable
      (cannot infer type-variable(s) R
        (actual and formal argument lists differ in length))
    method java.util.stream.Stream.<R,A>collect(java.util.stream.Collector<? super capture#2 of ? extends org.myeslib.core.Event,A,R>) is not applicable
      (cannot infer type-variable(s) R,A,capture#3 of ?,T,C,E
        (argument mismatch; java.util.stream.Collector<capture#2 of ? extends org.myeslib.core.Event,capture#4 of ?,java.util.LinkedList<capture#2 of ? extends org.myeslib.core.Event>> cannot be converted to java.util.stream.Collector<? super capture#2 of ? extends org.myeslib.core.Event,capture#4 of ?,java.util.LinkedList<capture#2 of ? extends org.myeslib.core.Event>>))

Apparently an existing bug , however already corrected (https://bugs.openjdk.java.net/browse/JDK-8051443), even with a java version of the error being updated still , how about the own builder LinkedList ?

```java
new LinkedList<>(this.events)
```

**Comment by rodolfodpk** [comment]
Seems to be working now.
